### ISSUE TITLE
the first few sentences make sense and then it's just rubbish

### ISSUE THREAD

**Issue by ErykCh** [OpenRouterTeam/openrouter-runner#100]
**Describe the bug**
The first few sentences make sense and then it's just rubbish.
This has happened to me a few times already and it's on the openrouter chat so it's not a problem with my application.

**To Reproduce**
Completely non-deterministic.

**Expected behavior**
Output from the model without any interference from the open router. Because this has happened to me on many different models. So it's not a problem of some supplier.

**Additional context**
This is link to the chat. I will try to not delete it:
https://openrouter.ai/chat?room=orc-KEfWUvaHNi15jxfXNvQCZxvAB3CX

![image](https://github.com/user-attachments/assets/8bb13def-9387-42ba-b317-4f0bef60ed2e)

**Comment by ErykCh** [comment]
once again
![image](https://github.com/user-attachments/assets/a52e1c71-0d1b-4c29-acfb-e30025abee81)

**Comment by ErykCh** [comment]
and again
![image](https://github.com/user-attachments/assets/bae96b40-a3ac-4a9e-8f6f-dbf7b1e30d1d)

**Comment by ErykCh** [comment]
link to the last one: https://openrouter.ai/chat?room=orc-yA1450swsUnhxAPryduBkaMGyz7E

**Comment by daun-io** [comment]
hi, thanks for repoting the issue! openrouter-runner repository is currently unrelated to our openrouter.ai product.
you might want to discuss it from our discord :>
