### ISSUE TITLE
wrong with  shell AI website

### ISSUE THREAD

**Issue by onlyhuman028** [OpenRouterTeam/openrouter-runner#95]
**Describe the bug**

**To Reproduce**
If applicable, provide steps to reproduce the behavior:

**Expected behavior**

**Additional context**

**Comment by onlyhuman028** [comment]
I have integrated a shell AI website, and the basic address has been filled in. However, I've noticed that it is unstable, sometimes accessible but mostly not. Could you please tell me the reason and how to resolve this issue? Your prompt response is greatly appreciated

**Comment by alexanderatallah** [comment]
Closing due to lack of information and no PR description
